Vagrant.configure("2") do |config|

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http = ENV['HTTP_PROXY']
    config.proxy.https = ENV['HTTPS_PROXY']
    config.proxy.ftp = ENV['FTP_PROXY']
    config.proxy.no_proxy = ENV['NO_PROXY']
  end

end
